### ISSUE TITLE
How to import playlists generated by third parties into ffplayout

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#29]
Hi !
I ask you if it is possible to import a playlist in .txt format (generated by a music scheduling program) into "ffplayout", and like this:

clip001.mp4
clip005.mp4
clip103.mp4
...
Specifically, if the exact duration of the video clips can be omitted (in the text format playlist).
thank you

**Comment by jb-alvarado** [comment]
With a little bit of programming it is possible. The GUI has a api, and to this api you can send your data.

Here are a bit of code to illustrate you, how it would work:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json

import requests
import urllib3

urllib3.disable_warnings()

SAVE_URL = 'https://example.org'


def auth():
    login = {'username': 'user',
             'password': 'password'}

    req = requests.post(
        '{}/auth/token/'.format(SAVE_URL), data=login)
    token = req.json()
    return token['access']


if __name__ == '__main__':
    # TODO: your logic to create playlist data

    req = requests.post(
        '{}/api/player/playlist/'.format(SAVE_URL),
        data=json.dumps({'data': playlist}),
        headers={'Authorization': 'Bearer {}'.format(auth()),
                 'content-type': 'application/json'})

    if req.status_code == 201:
        print('Save remote playlist from done...')
    else:
        print(req.json()['detail'])
```

There where the *TODO* command is, you have to put your code to create your json data. For getting the duration you can use the code I used in [ffplayout-engine](https://github.com/ffplayout/ffplayout-engine/blob/master/ffplayout/utils.py#L523), or you use the [mediainfo module](https://github.com/ffplayout/ffplayout-gui/blob/master/ffplayout/apps/api_player/utils.py#L269) which I use in the GUI.

**Comment by chicco64** [comment]
Hi !
Thank you for your answer, but I'm afraid I won't be able to work out the correct script on my own without your help.
With a "standard scheduling program" I can easily generate a txt file like the one shown below (source, in, out, duration)
how should I convert it to your format and export it, from my studio pc to "ffplayout" in the cloud, without using, for example, sftp?
Could you provide us with the complete script? I think it will be a useful tool for young ffplayout developers. 

[2020-08-31.txt](https://github.com/ffplayout/ffplayout-gui/files/5149617/2020-08-31.txt)

**Comment by jb-alvarado** [comment]
This is really not that difficult.
> without using, for example, sftp?
For that is the API. Everything what you can control in the GUI, you can also control over the API.

You can try this [scrip](https://raw.githubusercontent.com/ffplayout/ffplayout-gui/master/docs/send_playlist.py).

To get this to work you need the mediainfo library in your system and you need the python module **pymediainfo** and **requests**.

Your text file should only have the paths to the clips like:

```
/opt/ffplayout/media/clip1.mp4
/opt/ffplayout/media/clip2.mp4
```

And that paths must be found on the cloud server.

Then you can run the script with:

```
python send_playlist.py -u USER -p PASSWORD --url https://example.org -d 2020-08-31 -f INPUT.txt
```

**Comment by chicco64** [comment]
Hi !
i built a new debian 10 virtual machine inside the server hosting ffplayout (10.50.0.1)
your script in "send_playlist.py"
the playlist in the required format "INPUT.txt"
I installed the following modules:

# sudo apt-get install python-pymediainfo-doc
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pymediainfo-doc is already the newest version (3.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-------------------
root@localhost:~# pip3 install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)

root@localhost:~# apt-get install mediainfo
Reading package lists... Done
Building dependency tree
Reading state information... Done
mediainfo is already the newest version (18.12-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-----------------------------
# python send_playlist.py -u admin -p PASSWORD --url http://10.50.0.1 -d 2020-08-31 -f INPUT.txt

but an error message comes out:

Traceback (most recent call last):
  File "send_playlist.py", line 9, in <module>
    from pymediainfo import MediaInfo
ImportError: No module named pymediainfo

maybe something is still missing from the installation.

**Comment by jb-alvarado** [comment]
`pip3 install pymediainfo requests`

**Comment by chicco64** [comment]
same error 

Traceback (most recent call last):
  File "send_playlist.py", line 9, in <module>
    from pymediainfo import MediaInfo
ImportError: No module named pymediainfo

**Comment by jb-alvarado** [comment]
Maybe this helps:

```
apt install libmediainfo-dev
```

**Comment by chicco64** [comment]
same error

Traceback (most recent call last):
  File "send_playlist.py", line 9, in <module>
    from pymediainfo import MediaInfo
ImportError: No module named pymediainfo

**Comment by jb-alvarado** [comment]
Have you `/usr/lib/x86_64-linux-gnu/libmediainfo.so.0` in your system? 

Maybe this packages install all deps? `python3-pymediainfo`

**Comment by chicco64** [comment]
Have you /usr/lib/x86_64-linux-gnu/libmediainfo.so.0 in your system?
yes, i confirm this

**Comment by jb-alvarado** [comment]
Hm, maybe a logout and re-login? At the moment I don't know why this is happen.

**Comment by chicco64** [comment]
if i write:
# python3 send_playlist.py -u admin -p PASSWORD --url http://10.50.0.1 -d 2020-08-31 -fINPUT.txt

this is the result:
Traceback (most recent call last):
  File "send_playlist.py", line 100, in <module>
    playlist = gen_playlist()
  File "send_playlist.py", line 88, in gen_playlist
    duration = get_video_duration(src)
  File "send_playlist.py", line 64, in get_video_duration
    media_info = MediaInfo.parse(clip)
  File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 312, in parse
    with open(filename, "rb"):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ffplayout/media/clip1.mp4'

**Comment by jb-alvarado** [comment]
Yes that is a bit tricky: the paths need to exist locally where you generate the playlist and remote on ffplayout.

**Comment by chicco64** [comment]
Hi !
i tried to install "send_playlist.py" on debian virtual machine hosting ffplayout but the error is still the same.
Changing the username and password doesn't change anything, does authentication work? I wait for your instructions. thank you.

**Comment by jb-alvarado** [comment]
Which error is the same? This one?: `FileNotFoundError: [Errno 2] No such file or directory: '/opt/ffplayout/media/clip1.mp4'`

That just mean, that the clip in your text file not exist.

**Comment by chicco64** [comment]
NOW WORKS !!!!

# python3 send_playlist.py -u admin -p PASSWORD --url http://10.50.0.1 -d 2020-09-01 -f INPUT.txt

The /opt/ffplayout/media folders containing the .mp4 files on both virtual machines (remote "10.50.0.2" and host "10.50.0.1") 
must be synchronized and the same.
Otherwise, the remote machine cannot calculate the length of the mp4 files.
It could be NOT a limit. A back-up of the files (locally and in the cloud) is useful.
I hope I understand correctly.
