### ISSUE TITLE
create a 2 hour playlist on a loop every day

### ISSUE THREAD

**Issue by pegases** [ffplayout/ffplayout-frontend#30]
hello I have a 2 hour flow, is it possible to make a flow that loops over 24 hours
and copy 7 day

**Comment by jb-alvarado** [comment]
Hello, do I understand you right, that you have clips for 2 hours, and you want to loop them endless? 

This I have mentioned here: [Different-Ways-of-Playlist-Handling](https://github.com/ffplayout/ffplayout-engine/wiki/Different-Ways-of-Playlist-Handling) 

The only downside is, that you can not control this playlist by the GUI.
