### ISSUE TITLE
ffplayout with NAT authentication failed

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#31]
I created a NAT to the virtual machine hosting "ffplayout" (internal IP 10.50.0.1) to Public IP (port 80) with pfsense.
If I now enter the login credentials from the Public IP address, I get the "invalid credentials" error.
I believe you need to change the initial IP address entered during installation.
Where is the file containing the IP address 10.50.0.1 located?
Or how can I solve the problem?
thank you

**Comment by jb-alvarado** [comment]
In this cases is better to work with domains, instead of IPs. 

There is two files, where this infos are stored:
1. `/etc/nginx/sites-available/ffplayout.conf`
2. `/var/www/ffplayout/ffplayout/settings/production.py`

**Comment by chicco64** [comment]
Hi !
I just change the following and authentication through NAT works:

2. "/var/www/ffplayout/ffplayout/ffplayout/settings/production.py"

ALLOWED_HOSTS = ['localhost', '10.50.0.1', 'PUBLIC IP']

However, I noticed that, regardless of adding the public IP address, "often" to the "logout" of ffplayout, the error 
message "request failed with status code 400" appears

<img width="721" alt="Capture1" src="https://user-images.githubusercontent.com/59960414/91970209-36542d00-ed0f-11ea-9401-afc4d2b7949d.PNG">

Obviously this doesn't affect how ffplaout works, but it would be nice to get rid of it if possible.
Let me know.thanks

**Comment by jb-alvarado** [comment]
This is a bug. It will not affect security or usability. I will try to fix this.
