### ISSUE TITLE
ffmpeg param optimization for different video resolutions

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#32]
Hi !
I would like to know what are the (recommended) parameters for an optimal functioning of ffplayout, 
in case the following different resolutions are used:

1.   720p (1280×720)  
2.   480p (854×480)       
3.   360p (640×360) 

 *with better sound quality than currently in use (128k) if is possible

now, i used for all (1-2-3):

-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k

I also ask if it is possible to configure ffplayout to generate 2 rtmp streams to 2 different servers, and/or also if it is possible with two different video resolutions (e.g. 720p, 360p), to get an ABR stream.

let me know, thanks !

**Comment by jb-alvarado** [comment]
> `-c:v libx264 -crf 23`

This can be always the same, only when you notice artefacts, you can lower the **crf** number.

> `-x264-params keyint=50:min-keyint=25:scenecut=-1`

This should match your frame rate, when you use 25 FPS it is ok, when you use 20 FPS better use: `keyint=60:min-keyint=30:scenecut=-1`

> ` -maxrate 1300k -bufsize 2600k`

Here you have to try a bit to get the best result. For 720p it have to be higher, maybe 2400k and 4800k and for 360p the rate can be lower. You can read the ffmpeg [wiki](https://trac.ffmpeg.org/wiki/Limiting%20the%20output%20bitrate) for that.

> `-preset medium`

Adjust this to your [system power](https://trac.ffmpeg.org/wiki/Encode/H.264)

> `-profile:v Main -level 3.1`

This can be always the same.

> `-c:a aac -ar 44100 -b:a 128k`

Adjust this to your needs.

**Comment by jb-alvarado** [comment]
> I also ask if it is possible to configure ffplayout to generate 2 rtmp streams to 2 different servers, and/or also if it is possible with two different video resolutions (e.g. 720p, 360p), to get an ABR stream.

Both is possible. For having only two different targets you can use the [tee](https://ffmpeg.org/ffmpeg-formats.html#tee) muxer.

For different resolutions you have to add all options after the first output address again. And for every outout you have to higher the **output_count** option.

Let's say you want to have tree resolutions (1080p, 720p, 360p):
- set **output_count** to 3
- set processing width and hight to 1080p 
- add second and third output settings to **stream_output**:
    - `... -map vout2 -map aout2 -s 1280x720 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 2600k -bufsize 4800k -preset medium -profile:v Main -level 3.1 -c:a libfdk_aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://stream.daswort.tv/live/middle  -map vout3 -map aout3 -s 640x360 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 600k -bufsize 1200k -preset medium -profile:v Main -level 3.1 -c:a libfdk_aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://stream.daswort.tv/live/low`
    - don't forget the map options, that is important.

**Comment by chicco64** [comment]
Hi! 
unfortunately it does not work, I think I have definitely done something wrong.
In the meantime, let's try with 2 different bitrates (1280x720 and 640x360)
I am attaching my ffplayout.yml file

[ffplayout.yml.txt](https://github.com/ffplayout/ffplayout-gui/files/5163426/ffplayout.yml.txt)

thanks for your attention

**Comment by jb-alvarado** [comment]
Ok, my fault... Change **output_count** back to **1**, and remove the `-map vout2 -map aout2` command from **stream_output**.

**Comment by chicco64** [comment]
HI !
now it works perfectly ! great !
I ask you now if ffplayout can generate the rtmp stream in x265 HEVC.
if so, what are the parameters to modify.
thank you.

**Comment by jb-alvarado** [comment]
> I ask you now if ffplayout can generate the rtmp stream in x265 HEVC.

h265 is not in the rtmp specification, so ffmpeg does not support this codec in rtmp.

**Comment by chicco64** [comment]
I didn't know .. I'm sorry
using the "udp" stream, could this be possible?

**Comment by jb-alvarado** [comment]
You can use everything what ffmpeg support. A good starting point for it is the [ffmpeg wiki](https://trac.ffmpeg.org/wiki/StreamingGuide)
