### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by jrsmile** [ffplayout/ffplayout-frontend#33]
Hi, could you make the dependency for systemd optional?
im trying to get it working in a docker container but the install script needs systemd to run.

something like this, i did with ffplayout-engine

[ffplayout.zip](https://github.com/ffplayout/ffplayout-gui/files/5192628/ffplayout.zip)

**Comment by jb-alvarado** [comment]
Hi,
I need a solution for controlling the engine: start, stop, restart. And also the possibility that it always start new when it crashes. For this I use systemd. But when there is another way, I'm willing to integrate this.

**Comment by jrsmile** [comment]
Hi please have a Look at Supervisord, it does exactly what you want and is distro agnostic.

**Comment by jb-alvarado** [comment]
I think I only need Supervisord, when I run multiple processes at one inside the same container.

My though was, I create multiple Containers (maybe with compose):
- one for the engine
- one for API -> I would use the API from ffplayout-gui, not from messenger
- one for the GUI

But then I have the problem, how can I control the process inside the engine container, from the GUI container.

Until now I have not work with docker, so my knowledge is limited...

**Comment by jb-alvarado** [comment]
Maybe you are interested: I have start a new [project](https://github.com/ffplayout/ffplayout-docker) where I'm building a docker solution. For controlling the engine I though I create a little socket server, and run it with supervisord.

It looks like, that you have more experience in that area, so maybe you can give me some suggestions.

**Comment by jrsmile** [comment]
sure, this helps me as well as i currently use your script in a container i self manage.

im currently at work, but this evening i write you a little bit about my experiences with docker.

thanks for asking.

**Comment by jrsmile** [comment]
sooo, first of all when you don't have any experience with docker, it helped me to understand that a container is not a vm. in a vm the whole os is seperated from the host and there are little to no differences between two seperate machines as to a vm running on a host. With docker it is a whole different story...

docker is a combination of lxc and other methods to encapsulate different parts of the system into a jail with defined inputs and outputs. however there are configuration options to open parts of the jail back up to the host or other containers. Be it either for storage, networking, the process tree or the kernel.

the docker daemon is responsible for answering the docker client commands and creating rulesets to form these jails.
the abstraction of the filesystem allows downloading of programs and executing them in their jail without letting them know on what kind of host they are running.

to manage multiple container configurations you can use docker-compose.
this is a standalone binary that communicates with the docker client which forwards the commands to the docker daemon. either via unix socket **/var/run/docker.sock** or tcp connection.

to be able to control docker processes you must have access to the socket or the tcp endpoint provided by docker daemon.

fortunately you can configure a jail (container) to allow access to the socket by running a container with the parameter **-v /var/run/docker.sock:/var/run/docker.sock** as you might have guessed the first part is the host path the second part is the path in the container. 

however this is very danerous, if you use docker for security reasons you allow full control of the host by the container.
this is incredible dangerous as the docker daemon can change any file the user the docker daemon runs as has access to, which in most cases is root.

there are other options like networks and exposed ports which are just fancy words for joined jails.

two containers can talk to each other via file or network connections you have defined in your docker-compose file.

in addition it is possible to ad so called volumes, you can think of them as filesystem jails which can be mounted to multiple containers. so for example if you mount a data volume to container "ftp uploader" and to "ffplayout-engine" you could  have a ftp server running ubuntu for uploads and a ffplayout engine running on debian accessing the uploads. all without the host knowing there are files somewere.

by making the volume persistent it wont get deleted if you delete or switchout a container with a different version the the uploads are safe.

i attached a sample config (cleaned a bit of secrets) from one of my docker hosts.


[Docker-Compose.yml.txt](https://github.com/ffplayout/ffplayout-frontend/files/5203730/Docker-Compose.yml.txt)

don't be overwelmed the file is mostly split in two sectors.

**services** (containers) and **volumes**.
every service starts with its name followed by the image it is build from.
the **command** parameter defines the start parameters of the container (and most of the time the process int the container).
**environment variables and labels** are container specific and have no standart in the docker world.
but they are priceless when it comes to configuring a container which was not build by you.
there are some really good container solutions out there.
take traeffik for example. you mount /var/run/docker.sock into it to allow autoconfiguration of a port 80+443 reverse proxy for every container you start.
the labels help traeffic to configure the reverse-proxy rules for the container correctly.

**links** are virtual lan cables which connect two different containers into one private subnet for internal communication.
in the example i start more then 15 servers but on the host the only ports that are visible to the outside world are 80 443 and a elasticstack port 9200 which is blocked by the host firewall from outside.

then there are the **ulimits** you can limit containers by default for cpu, ram or open files usage but excemt them via the config to make them unrestricted.

there is even a little logic possible while starting and stopping containers, if you define the **depends_on** attibute you can make sure a container is only started if another container is already running. for a example you start a webserver after a db server is online although you started them with the same docker-compose.yml

feel free to ask questions, im not a native english speaker so there might be some hickups. :-)

**Comment by jb-alvarado** [comment]
Thank you for your very detailed explanation, it helps me much!

You where explaining about volumes: I would like to use the same mount point for ffplayout-engine, ffplayout-api, but I also want to have access to them from my host. Is this a problem? And is this volumes are the same then when you using `docker --volume /mnt/share:/tv-media ...`?

And can you give a a hint, why I get cors header errors, when I try to use the api from the frontend? Here are the current project:

https://github.com/ffplayout/ffplayout-docker

**Comment by jrsmile** [comment]
yes it is possible to use the same mount point for multiple containers and the host simply define a path.
**docker run -v /opt/mediaStorage:/opt/mediaStorage ffplayout-engine
docker run -v /opt/mediaStorage:/opt/mediaStorage ffplayout-api
docker run -v /opt/mediaStorage:/opt/mediaStorage ffplayout-frontend**

the files will then be on the host under /opt/mediaStorage

if you don't want to have the files on the host you could use 

**docker volume create ffplayout_data

docker run -v ffplayout_data:/opt/mediaStorage ffplayout-engine
docker run -v ffplayout_data:/opt/mediaStorage ffplayout-api
docker run -v ffplayout_data:/opt/mediaStorage ffplayout-frontend**

if you want to have a ui for managing containers and volumes i recomend portainer.

**docker volume create portainer_data
docker run -d -p 9000:9000 -p 8000:8000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer**

if started there will be a webinterface on your server on port 9000 were you can set an initial password and get an overview of you docker host.

**Comment by jb-alvarado** [comment]
I found the CORS problem: I made the mistake to use the wrong IP for allowing CORS in django. When later everything runs in its own docker network, and with the correct proxy settings, it become more easy an generic.

**Comment by jb-alvarado** [comment]
Done in https://github.com/ffplayout/ffplayout-docker
