### ISSUE TITLE
ffplayout with loudnorm

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#34]
Hi,
would like a clarification for the use of "loudnorm"
I see that you can select the "realtime" option, I can't appreciate the difference, which mode do you suggest?
thanks

**Comment by jb-alvarado** [comment]
The realtime option has nothing to do with loudnorm. It is a filter which slowdown the compression task to a playable speed. Like `-re` options. This is only important for hls output.
