### ISSUE TITLE
ffplayout VOD management 

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#35]
I ask you if it is possible to "extract" or make the single .mp4 contents uploaded in FFPLAYOUT as VOD available on the network.
thanks

**Comment by jb-alvarado** [comment]
Sorry I don't understand your question. Can you explain this?

**Comment by jb-alvarado** [comment]
I don't see any problem in that. Yes you can expose the files to your VOD page, and also to the playout.
