### ISSUE TITLE
Не работает автоустановщик.

### ISSUE THREAD

**Issue by linnikvv** [ffplayout/ffplayout-frontend#37]
Доброго времени суток. Ваш скрипт **install.sh** не работает на **debian 10** и закрывается с ошибкой на шаге сборки **ffmpeg** и в на последнем этапе не создаётся файл **ffplayout.conf /etc/nginx/sites-enabled/**, всё делал согласно вашей инструкции. А также не получается установить на Ubuntu 18.04-20.04. Помогите пожалуйста с установкой или внесите изменения, буду очень благодарен.)  Попробуйте пожалуйста установить на своей машине с debian 10.

**Comment by jb-alvarado** [comment]
Sorry, but please write in English.
