### ISSUE TITLE
HLS 404

### ISSUE THREAD

**Issue by linnikvv** [ffplayout/ffplayout-frontend#38]
Hello, please tell me why the link /live/stream.m3u8 is not available? The installation was performed using install.sh

**Comment by linnikvv** [comment]
nginx log
`2020/10/21 15:19:07 [error] 25213#25213: *161 open() "/var/www/ffplayout-frontend/dist/live/stream.m3u8" failed (2: No such file or directory), client: myip, server: mysite.com, request: "GET /live/stream.m3u8 HTTP/1.1", host: "mysite.com", referrer: "https://mysite.com/player"`

**Comment by linnikvv** [comment]
![Снимок экрана 2020-10-21 152620](https://user-images.githubusercontent.com/72468949/96719250-d3e3e880-13b1-11eb-87db-bf392e6215e2.png)

**Comment by jb-alvarado** [comment]
When you install SRS check if the path `/var/www/srs` is in your nginx config.

**Comment by linnikvv** [comment]
ffplayout.conf
`server {

    server_name mysite.com;

    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    charset utf-8;

    client_max_body_size 70000M; # should be desirable value

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        if ($http_origin ~ '^https?://(localhost|mysite\.com)') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
        }

        if ($request_method = OPTIONS ) {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        root /var/www/ffplayout-frontend/dist/;

    }

    location ~ ^/(api|admin|auth|api-auth) {
        if ($http_origin ~ '^https?://(localhost|mysite\.com)') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
        }

        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 36000s;
        proxy_connect_timeout 36000s;
        proxy_send_timeout 36000s;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        send_timeout 36000s;
        proxy_no_cache 1;
        proxy_pass http://127.0.0.1:8001;

    }

    location /static/ {
        alias /var/www/ffplayout-api/ffplayout/static/;
    }
	

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mysite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;

    server_name mysite.com;
    return 404; # managed by Certbot


}
`
nginx.conf
`user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
`
Media upload page and folder creation not working.
Error 500

**Comment by linnikvv** [comment]
Error creating folder and loading media files

![Снимок экрана 2020-10-22 102814](https://user-images.githubusercontent.com/72468949/96839050-51126a80-1451-11eb-975a-890ae5d37d54.png)

**Comment by jb-alvarado** [comment]
For the folder/file creation: check the permission and owner from media folder. Which operation system you have?

**Comment by linnikvv** [comment]
debian 10
media - 755
clip - 755

**Comment by jb-alvarado** [comment]
And the owner is www-data?

**Comment by linnikvv** [comment]
root

**Comment by jb-alvarado** [comment]
It should be **www-data**

**Comment by linnikvv** [comment]
Added this to ffplayout.conf
location / live / {
        alias / var / www / srs / live /;
    }
Error 404

**Comment by jb-alvarado** [comment]
You have in the config also spaces in the path?

**Comment by linnikvv** [comment]
No. And now no .ts and .m3u8 files are created
![Uploading Снимок экрана 2020-10-22 112310.png…]()

**Comment by linnikvv** [comment]
Question about advertising what happens if I choose ad?

**Comment by jb-alvarado** [comment]
is srs running and is the engine streaming to it?

When you choose ad for a clip the logo will be hidden.

**Comment by linnikvv** [comment]
I figured it out with srs, thanks a lot for your help)

**Comment by linnikvv** [comment]
![Снимок экрана 2020-10-22 115651](https://user-images.githubusercontent.com/72468949/96848945-b3716800-145d-11eb-8015-8f3dd56300c3.png)

**Comment by jb-alvarado** [comment]
Have you compile ffmpeg with **libzmq**?

**Comment by linnikvv** [comment]
![Снимок экрана 2020-10-22 120906](https://user-images.githubusercontent.com/72468949/96850379-68f0eb00-145f-11eb-857f-6c0629c4255b.png)

**Comment by jb-alvarado** [comment]
Maybe you need to activate the text in the config.

**Comment by linnikvv** [comment]
![Uploading Снимок экрана 2020-10-22 122127.png…]()

**Comment by linnikvv** [comment]
![Снимок экрана 2020-10-22 122127](https://user-images.githubusercontent.com/72468949/96851852-27613f80-1461-11eb-8081-0cbeab401f35.png)

**Comment by jb-alvarado** [comment]
Deactivate **over_pre**. This is only for direct hls output.

**Comment by linnikvv** [comment]
Disconnected but it didn't help

**Comment by jb-alvarado** [comment]
And after changing you restart the engine?

**Comment by linnikvv** [comment]
the engine did not restart.

**Comment by jb-alvarado** [comment]
You can do it on the player page.

**Comment by linnikvv** [comment]
It turned out, thanks a lot)
And another question, is it possible to do so that the opening that was at 23:59 was postponed to the next day and continued?

**Comment by jb-alvarado** [comment]
You mean a endless loop?

**Comment by linnikvv** [comment]
Suppose that the video runs for 1 hour and it started at 23:50 how to transfer the remaining time of the video to the next day and save the playlist function, instead of filling the remaining time with short videos? Is that possible?

**Comment by jb-alvarado** [comment]
I hope I understand you correctly. When the playlist start is at 0:00 the last video cannot go over 24:00. Then you need to have different day start time. Beside this the engine and the GUI can only handle 24/7 playlist correctly. When you want them shorter, you need to work with a cronjob.

**Comment by linnikvv** [comment]
That is, you won't be able to implement it?

**Comment by jb-alvarado** [comment]
At the moment there is no plan for that.

**Comment by linnikvv** [comment]
Too bad!
