### ISSUE TITLE
metadata stream

### ISSUE THREAD

**Issue by linnikvv** [ffplayout/ffplayout-frontend#39]
![Снимок экрана 2020-10-24 005659](https://user-images.githubusercontent.com/72468949/97057430-d9008d80-1593-11eb-9e49-6511bcd3a0f4.png)

how to pass metadata to stream_output?

**Comment by jb-alvarado** [comment]
There is a [metadata parameter](https://ffmpeg.org/ffmpeg-all.html#Main-options)
