### ISSUE TITLE
Playlist management

### ISSUE THREAD

**Issue by Marco-LB** [ffplayout/ffplayout-frontend#40]
hello I wanted to ask if it was possible to create a button within the playlist management in order to copy the playlists from the gui without going to create them for every single day from time to time via drag and drop.
for example a copy and paste video in to another day

**Comment by jb-alvarado** [comment]
Is done in dev branch.

**Comment by edwoodza** [comment]
+1 on this one as well

**Comment by Marco-LB** [comment]
Hi, thanks a lot!!!!!!!!!!!!!!
