### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout-frontend#41]
I tried to install on centos, ubuntu, Debian,
but I am getting: "Error: Request failed with status code 500" when I try to log in.

could you please tell me what could be the issue?

**Comment by peppi001** [comment]
I've got the same error on Debian9 and Debian10.

**Comment by jb-alvarado** [comment]
I'm working at the moment on new features, so it could be possible that I break some things. When you are using from all repos only the released versions it should work.

**Comment by peppi001** [comment]
I used "install.sh" to install.

**Comment by jb-alvarado** [comment]
I have to check the install script, maybe it is broken.

**Comment by peppi001** [comment]
Thanks

**Comment by dfranje** [comment]
I have also used the install.sh from ffplayout_fontend.

when i go to django Administration, i can normaly log in. Pleas let us know when you have some info. Great work by the way!

**Comment by dfranje** [comment]
Update... Now its throwing error code 400
![Screenshot_20210112-121233_Chrome](https://user-images.githubusercontent.com/77287374/104307755-ef9ded00-54cf-11eb-93a1-5595e2fdf501.jpg)

**Comment by jb-alvarado** [comment]
I have create a new [installer repo](https://github.com/ffplayout/ffplayout-installer). You can try this one, it gets the right versions.

**Comment by dfranje** [comment]
now im geting this:

./install.sh: line 35: /opt/ffplayout-installer/scripts/system.sh: No such file or directory

------------------------------------------------------------------------------
compile and install (nonfree) ffmpeg:
------------------------------------------------------------------------------

Do you wish to compile ffmpeg? (Y/n) :$ y
./install.sh: line 59: /opt/ffplayout-installer/scripts/ffmpeg.sh: No such file or directory

------------------------------------------------------------------------------
install and srs rtmp/hls server:
------------------------------------------------------------------------------

Do you wish to install srs? (Y/n) :$ y
./install.sh: line 83: /opt/ffplayout-installer/scripts/srs.sh: No such file or directory

------------------------------------------------------------------------------
path to media storage, default: /opt/tv-media
------------------------------------------------------------------------------

media path :$ /opt/tv-media

------------------------------------------------------------------------------
playlist path, default: /opt/playlists
------------------------------------------------------------------------------

playlist path :$ /opt/playlists
./install.sh: line 111: /opt/ffplayout-installer/scripts/engine.sh: No such file or directory
./install.sh: line 112: /opt/ffplayout-installer/scripts/api.sh: No such file or directory
./install.sh: line 113: /opt/ffplayout-installer/scripts/frontend.sh: No such file or directory

**Comment by jb-alvarado** [comment]
Ah sorry, I should explain this in Readme... You need to go to **/opt/** and clone there the **ffplayout-installer** repo.

**Comment by dfranje** [comment]
Unfortunately no success.
The same problem occurs.

"STATUS CODE 400"

Currently, on ubuntu 18.04 , centos lot of errors for me occurred.

https://prnt.sc/wm0d4w

@jb-alvarado  if you want i will glady give you the server credentials so you can have a look.

**Comment by peppi001** [comment]
It works now! Thanks

If error 400:
Change to
ALLOWED_HOSTS = ['*']
in
/var/www/ffplayout-api/ffplayout/ffplayout/settings/production.py

**Comment by dfranje** [comment]
@peppi001  thanks, I have changed the field, but still the same issue.

I'm working on a small VPS . 

any other ideas?

**Comment by jb-alvarado** [comment]
Have you see anything in the installation process, that there where any errors? Tomorrow I can try it on a ubuntu vm. Maybe 18.04 is to old? CentOS was not tested.

Can you show the service status:
```
systemctl status ffplayout-engine
systemctl status ffplayout-api
systemctl status srs
systemctl status nginx
```

**Comment by dfranje** [comment]
root@vmi306360:~# **systemctl status ffplayout-engine**
● ffplayout-engine.service - python and ffmpeg based playout
   Loaded: loaded (/etc/systemd/system/ffplayout-engine.service; enabled; vendor preset: enabled)
   **_Active: active (running) since Tue 2021-01-12 20:00:23 CET; 32min ago_**
 Main PID: 405 (python)
    Tasks: 28 (limit: 4680)
   CGroup: /system.slice/ffplayout-engine.service
           ├─ 405 /opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py
           ├─ 445 ffmpeg -v error -hide_banner -nostats -re -thread_queue_size 256 -i pipe:0 -metada
           └─2113 ffmpeg -v error -hide_banner -nostats -f lavfi -i color=c=#121212:s=1024x576:d=30:

Jan 12 20:00:23 vmi306360.contaboserver.net systemd[1]: Started python and ffmpeg based playout.
lines 1-11/11 (END)


root@vmi306360:~# systemctl status ffplayout-api
● ffplayout-api.service - ffplayout api daemon
   Loaded: loaded (/etc/systemd/system/ffplayout-api.service; enabled; vendor preset: enabled)
   **_Active: active (running)_** since Tue 2021-01-12 20:00:23 CET; 33min ago
 Main PID: 403 (gunicorn)
    Tasks: 5 (limit: 4680)
   CGroup: /system.slice/ffplayout-api.service
           ├─403 /var/www/ffplayout-api/venv/bin/python3 /var/www/ffplayout-api/venv/bin/gunicorn --
           ├─463 /var/www/ffplayout-api/venv/bin/python3 /var/www/ffplayout-api/venv/bin/gunicorn --
           ├─464 /var/www/ffplayout-api/venv/bin/python3 /var/www/ffplayout-api/venv/bin/gunicorn --
           ├─465 /var/www/ffplayout-api/venv/bin/python3 /var/www/ffplayout-api/venv/bin/gunicorn --
           └─466 /var/www/ffplayout-api/venv/bin/python3 /var/www/ffplayout-api/venv/bin/gunicorn --

Jan 12 20:27:49 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:27:49 +0000
Jan 12 20:27:49 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:27:49 +0000
Jan 12 20:27:51 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:27:51 +0000
Jan 12 20:27:51 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:27:51 +0000
Jan 12 20:28:01 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:01 +0000
Jan 12 20:28:01 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:01 +0000
Jan 12 20:28:03 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:03 +0000
Jan 12 20:28:03 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:03 +0000
Jan 12 20:28:06 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:06 +0000
Jan 12 20:28:07 vmi306360.contaboserver.net gunicorn[403]: 127.0.0.1 - - [12/Jan/2021:19:28:07 +0000
lines 1-22/22 (END)


root@vmi306360:~# systemctl status srs
● srs.service - SRS
   Loaded: loaded (/etc/systemd/system/srs.service; enabled; vendor preset: enabled)
   **_Active: active (running)_** since Tue 2021-01-12 20:00:22 CET; 34min ago
     Docs: https://github.com/ossrs/srs/wiki
  Process: 424 ExecStart=/usr/local/srs/objs/srs -c /etc/srs/srs.conf (code=exited, status=0/SUCCESS
  Process: 397 ExecStartPre=/usr/local/srs/objs/srs -t -c /etc/srs/srs.conf (code=exited, status=0/S
 Main PID: 427 (srs)
    Tasks: 1 (limit: 4680)
   CGroup: /system.slice/srs.service
           └─427 /usr/local/srs/objs/srs -c /etc/srs/srs.conf

Jan 12 20:00:23 vmi306360.contaboserver.net srs[397]: [2021-01-12 20:00:23.595][Trace][397][0] devic
Jan 12 20:00:23 vmi306360.contaboserver.net srs[397]: [2021-01-12 20:00:23.595][Warn][397][0][0] sta
Jan 12 20:00:23 vmi306360.contaboserver.net srs[397]: [2021-01-12 20:00:23.595][Warn][397][0][0] sta
Jan 12 20:00:23 vmi306360.contaboserver.net srs[397]: [2021-01-12 20:00:23.595][Trace][397][0] write
Jan 12 20:00:23 vmi306360.contaboserver.net srs[397]: [2021-01-12 20:00:23.595][Trace][397][0] confi
Jan 12 20:00:22 vmi306360.contaboserver.net srs[424]: [2021-01-12 20:00:22.699][Trace][424][0] XCORE
Jan 12 20:00:22 vmi306360.contaboserver.net srs[424]: [2021-01-12 20:00:22.700][Trace][424][0] confi
Jan 12 20:00:22 vmi306360.contaboserver.net srs[424]: [2021-01-12 20:00:22.700][Warn][424][0][0] tra
Jan 12 20:00:22 vmi306360.contaboserver.net srs[424]: [2021-01-12 20:00:22.700][Trace][424][0] write
Jan 12 20:00:22 vmi306360.contaboserver.net systemd[1]: Started SRS.
lines 1-21/21 (END)


root@vmi306360:~# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   **_Active: active (running)_** since Tue 2021-01-12 20:00:22 CET; 34min ago
     Docs: man:nginx(8)
  Process: 431 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUC
  Process: 406 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, sta
 Main PID: 434 (nginx)
    Tasks: 3 (limit: 4680)
   CGroup: /system.slice/nginx.service
           ├─434 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─435 nginx: worker process
           └─436 nginx: worker process

Jan 12 20:00:23 vmi306360.contaboserver.net systemd[1]: Starting A high performance web server and a
Jan 12 20:00:22 vmi306360.contaboserver.net systemd[1]: Started A high performance web server and a
lines 1-15/15 (END)

**Comment by jb-alvarado** [comment]
That looks good. Can you check nginx logs (access.log and error.log) and see what it says there.

**Comment by dfranje** [comment]
Well it urns out my vps was the problemm... I changed the server and everything installed ok. But now i have a nother issue. See the images. 
![20210113_185945](https://user-images.githubusercontent.com/77287374/104491036-f4e36080-55d1-11eb-955b-eabda71c515c.jpg)
![20210113_190002](https://user-images.githubusercontent.com/77287374/104491044-f7de5100-55d1-11eb-9f17-1b4c3b233549.jpg)
![20210113_190011](https://user-images.githubusercontent.com/77287374/104491050-fa40ab00-55d1-11eb-9e31-fa9dade6dbb0.jpg)

**Comment by jb-alvarado** [comment]
Have you install srs? When yes, what says `systemctl status srs`?

**Comment by dfranje** [comment]
Yes......
here is what i got 👍 


 srs.service - SRS
     Loaded: loaded (/etc/systemd/system/srs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2021-01-13 20:22:30 CET; 1s ago
       Docs: https://github.com/ossrs/srs/wiki
    Process: 8631 ExecStartPre=/usr/local/srs/objs/srs -t -c /etc/srs/srs.conf (code=exited, status=203/EXEC)

**Comment by jb-alvarado** [comment]
Hm, looks like that something is happen with it. Can you run: `journalctl -u srs`, and past the hole output here?

**Comment by dfranje** [comment]
`Last login: Wed Jan 13 23:10:23 2021 from 95.168.118.25
root@Ubuntu-2004-focal-64-minimal ~ # journalctl -u srs
-- Logs begin at Wed 2021-01-13 23:10:02 CET, end at Thu 2021-01-14 00:22:28 CET. --
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[166388]: srs.service: Failed to execute comman>
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[166388]: srs.service: Failed at step EXEC spaw>
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=>
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code>
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restar>
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[166460]: srs.service: Failed to execute comman>
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[166460]: srs.service: Failed at step EXEC spaw>
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=>
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code>
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restar>
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[166473]: srs.service: Failed to execute comman>
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[166473]: srs.service: Failed at step EXEC spaw>
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=>
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code>
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restar>
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[166482]: srs.service: Failed to execute comman>
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[166482]: srs.service: Failed at step EXEC spaw>
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=>
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code>
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restar>
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
lines 1-34...skipping...
-- Logs begin at Wed 2021-01-13 23:10:02 CET, end at Thu 2021-01-14 00:22:28 CET. --
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[166388]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[166388]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:07 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 1.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[166460]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[166460]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:10 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 2.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[166473]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[166473]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:14 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 3.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[166482]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[166482]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:17 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 4.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[166485]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[166485]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:20 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 5.
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[166487]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[166487]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Control process exited, code=exited, status=203/EXEC
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Failed with result 'exit-code'.
Jan 13 23:53:23 Ubuntu-2004-focal-64-minimal systemd[1]: Failed to start SRS.
Jan 13 23:53:27 Ubuntu-2004-focal-64-minimal systemd[1]: srs.service: Scheduled restart job, restart counter is at 6.
Jan 13 23:53:27 Ubuntu-2004-focal-64-minimal systemd[1]: Stopped SRS.
Jan 13 23:53:27 Ubuntu-2004-focal-64-minimal systemd[1]: Starting SRS...
Jan 13 23:53:27 Ubuntu-2004-focal-64-minimal systemd[166491]: srs.service: Failed to execute command: No such file or directory
Jan 13 23:53:27 Ubuntu-2004-focal-64-minimal systemd[166491]: srs.service: Failed at step EXEC spawning /usr/local/srs/objs/srs: No such file or directory`

**Comment by jb-alvarado** [comment]
SRS did not install...

Can you follow [this steps](https://github.com/ffplayout/ffplayout-installer/blob/main/scripts/srs.sh) manually?

And then `systemctl restart srs.service && systemctl status srs.service` and check the output.

**Comment by jb-alvarado** [comment]
There was an issue related to ubuntu. I updated the repo. When you want to do it by hand:
- install libssl-dev
- configure srs with: `./configure --use-sys-ssl`

**Comment by dfranje** [comment]
yes. now its all good, and working... can i get your email adress, i would like to speak to you in more detail about some enhancments,and my contibution to the project.

**Comment by jb-alvarado** [comment]
My address you get with `git log`
