### ISSUE TITLE
GUI displaying wrong playout info/ playlist issue

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#43]
Picked up what is being sent out encoded does not correspond with what the GUI playlist is showing.

Further to this GUI shows different things on firefox and chrome as well. (as per image)

Both browsers were reloaded and reloggedin as well to ensure updated info.

Running in docker.

![docker po gui error 8](https://user-images.githubusercontent.com/8553968/104564614-cf973680-5653-11eb-9ba0-5699deff61a6.png)

**Comment by jb-alvarado** [comment]
The current time can have a little shift, because the time get updated only all 5 seconds. That different clips a playing, I can not reproduce. Did you use playlist mode? and which day_start settings you are using?

**Comment by jb-alvarado** [comment]
When the starting time in general is wrong, then we have to adjust the time zone from container.

**Comment by edwoodza** [comment]
the differences between the 2 are massive. and neither are showing whats actually playing anyhow

![docker po gui error 9](https://user-images.githubusercontent.com/8553968/104566269-12f2a480-5656-11eb-9d83-1f606b76f69c.png)

**Comment by jb-alvarado** [comment]
Can you change length to 24:00:00? maybe the GUI got confuse with that.

**Comment by edwoodza** [comment]
will do. 
also found a bug that if you delete the time  you cant enter it back in correct notation on decimal. 
I had to cut and paste it back to get it to accept. (same issue in logo scale field as well)

**Comment by edwoodza** [comment]
> 
> 
> Can you change length to 24:00:00? maybe the GUI got confuse with that.

tried change made no difference.
playout is running and streaming but playlist shows nothing playing on all browsers yet its streaming.

**Comment by jb-alvarado** [comment]
I'm sure that one issue is, that the containers are using the wrong timezone. There are some ways to fix that, like here: https://stackoverflow.com/questions/39172652/using-docker-compose-to-set-containers-timezones

I think, I like the idea to link the timezone settings from host to containers. But even there you have to be sure that you using the right settings on your host.

**Comment by edwoodza** [comment]
It may be.
But currently i  shows nothing as playing and clocks all at 00:00:00 BUT the playlist is streaming.
almost like its looping output of playlist (thats shorter than the set 24 hours) BUT not updating the items being replayed?

**Comment by jb-alvarado** [comment]
Can be yes. The gui was mostly made for 24/7 streaming and all other options are not much tested nor had any weight.

**Comment by edwoodza** [comment]
I changed the start time of list and restarted and now it shows whats playing in GUI.
So it seems like after then less than 24 hour playlist ends. the system loops it BUT does not update GUI to show whats playing again from the start as it assumes file is played and done.

i see the video streaming is the playlist looping so this may be it?
so the GUI when hits end of playlist and auto loops needs to update in gui to start at the begining showing whats playing now? (may need to update times again by its self for it?)

**Comment by edwoodza** [comment]
yeah its something else.
i created a small playlist and it started and in a few min it was off
you can see the video shows Taipai but on the playout its saying another file.
the GUI seems to lag

![docker po gui error 10](https://user-images.githubusercontent.com/8553968/104575964-4c301200-5660-11eb-84c2-4b6a11eca729.png)

**Comment by edwoodza** [comment]
if its playingout and you restart the server it seems to present at that stage most.

**Comment by edwoodza** [comment]
Testing this again
1. confirmed a 24 hour playlist using the test files on git to be sure its not a file issue
2. saved playlist
3. restarted server to flush things incase

BUT in the logs i see this
[ERROR]  Playlist (2021-01-18) is not long enough! Total play time is: 0:03:25.560000, target length is: 1 day, 0:00:00

its viewing the 24 hour playlist as shorter it seems.
all that plays now is the filler clip

this is on debian10 (not docker)

**Comment by edwoodza** [comment]
rebooted and started testing again this am (20th)
playlist for 20th does not load

Logs shows
[ERROR]  Playlist (2021-01-19) is not long enough! Total play time is: 0:24:56.510000, target length is: 2:00:00

(length set to 2 hours for easy testing)

BUT today is the 20th and not 19th so not sure why its loading old file.

system date and time was checked and confirmed correct date and times on system.

I also earlier saw in the logs it was again verifying 19th playlist (today is 20th) and showed missing files in it. BUt again not sure why its checking playlist for playout for 19th when today 20th.

[ERROR]  Validation error, check JSON playlist, values are missing: File not exist: "/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4" In line: {'source': '/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4', 'in': 0, 'out': 3600.162, 'duration': 3600.162, 'category': ''}  File not exist: "/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4" In line: {'source': '/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4', 'in': 0, 'out': 3600.162, 'duration': 3600.162, 'category': ''}  File not exist: "/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4" In line: {'source': '/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4', 'in': 0, 'out': 3600.162, 'duration': 3600.162, 'category': ''}  File not exist: "/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4" In line: {'source': '/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4', 'in': 0, 'out': 3600.162, 'duration': 3600.162, 'category': ''}  File not exist: "/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4" In line: {'source': '/opt/tv-media/test-clips/AliceBlue_01-00-00.mp4', 'in': 0, 'out': 3600.162, 'duration': 3600.162, 'category': ''}  
[2021-01-20 06:31:50,361] 

The new playlist for 20th does not load.
logs not showing even checking it

-rw-r--r-- 1 www-data www-data 2263 Jan 18 10:44 2021-01-18.json
-rw-r--r-- 1 www-data www-data   75 Jan 20 06:45 2021-01-19.json
-rw-r--r-- 1 www-data www-data  925 Jan 20 06:41 2021-01-20.json
-rw-r--r-- 1 www-data www-data  526 Jan 20 06:21 2021-01-21.json
-rw-r--r-- 1 www-data www-data  486 Jan 20 06:23 2021-01-22.json

confirmed files being written and changed.

**Comment by jb-alvarado** [comment]
Please don't post your issues multiple times!

**Comment by jb-alvarado** [comment]
The ori

**Comment by edwoodza** [comment]
apologies. i posted it here 1st then realised would be best in its own ticket to avoid 2 issues in 1 ticket
