### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Marco-LB** [ffplayout/ffplayout-frontend#45]
hi with new release of ffplayout-frontend the file install.sh disappeared.

anyway I took the install.sh file in dev, and started the installation,
I use a proxmox container with debian 10, after the installation is finished if I try to go to the server's ip address I only see the nginx home page, where am I wrong?

**Comment by jb-alvarado** [comment]
Hi, I move the installer to a new repo: https://github.com/ffplayout/ffplayout-installer

**Comment by edwoodza** [comment]
@Marco-LB i get  a similar problem even when using the new https://github.com/ffplayout/ffplayout-installer repo
