### ISSUE TITLE
GUI does not display current items playing in playlist on day change

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#50]
Created 3 days 24 hour playlists.
day 1 (starting 8am) Plays perfectly as per schedule and shows whats playing correctly.

next morning (7am) playout is still playing as per schedule BUT the GUI does not show the file playing. 
It by default shows today's date (day2) playlist (which is not being played out till 8am)

If i click back a day to show day 1 playlist in the GUI and scroll down to the time of the clip on air it does not show its playing the file in the GUI (but stream output is)

Also in the GUI window where it shows the file playing it shows nothing as if its not playing out and no count down clock on file

BUT it is playing out. I can see the correct program on the stream output.

Server time and browser times are the same.

Its like with the day change (time of day) it breaks the link to whats playing until the new playlist is loaded by cron command. 
(is the cron run at the set playlist start time or a preset default time?)

It may be because my playlist start time is not 00:00:00

**Comment by jb-alvarado** [comment]
I need to test this behavior. Our starting time is at 6, so I never pay attention to that.

There is no cron running. The ffplayout-engine count the file duration's together and when the playlist length parameter is reached, it starts a new playlist. This calculation start with every clip again, that makes the playlist dynamical.

**Comment by jb-alvarado** [comment]
The fix has a limitation: In the GUI is no automatic transition to next day. It could interfere with playlist editing, that is way I have not integrate this.

**Comment by edwoodza** [comment]
so once playlist is made, the next day you can no see what is being played out in the schedule on the GUI or the next few days for that matter?

**Comment by jb-alvarado** [comment]
Of course you can see them. The only limitation is, that when the current playlist is almost done playing, the view is not changing automatically to the next day. For that you have to click on the calendar.

**Comment by edwoodza** [comment]
awesome. will load the patch and test next week.
Loving your work BTW
