### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#52]
On the GUI. I love the copy playlist to new day (VERY useful)
Some wish list requests

1. Like the click to copy to another day. could we have a click to repeat playlist for rest of 24 hours. eg you have say 4 hours in playlist, you click it and it repeats the 4 hours in loop in playlist until the 24 hours is full?

2. Option to be able to copy intems in playlist and repast them, rather than having to re drag and drop (if not the full above option 1 this can help alot as a mid way option)

**Comment by SoftwareMagicIT** [comment]
I suggest add in copy also multi days selection at same time. Or you can also add days of week buttons and set playlist for this. For mixed mode you need to check if date-related playlist exist and if not execute dayofweek playlist. This is only suggestion, if you want ; )
