### ISSUE TITLE
default username and password

### ISSUE THREAD

**Issue by MrPowerScripts** [ffplayout/ffplayout-frontend#54]
I'm having a hard time finding the default username and password to login to the site. also, is there a way to reset the password if it's forgotten?

**Comment by jb-alvarado** [comment]
- navigate to **/var/www/ffplayout-api/**
- run `source venv/bin/activate`
-  `cd ffplayout`
- run `python manage.py changepassword [your user name]`

**Comment by MrPowerScripts** [comment]
this was it! thank you!!!
