### ISSUE TITLE
folder showed and clickable in a folder

### ISSUE THREAD

**Issue by SoftwareMagicIT** [ffplayout/ffplayout-frontend#57]
![image](https://user-images.githubusercontent.com/16600519/112745739-ea1e5200-8faa-11eb-8ebf-b3459581540d.png)
Show tv-media and if I select, show always tv-media

**Comment by jb-alvarado** [comment]
Is this from master branch, or releases?

**Comment by SoftwareMagicIT** [comment]
in release I used installer script

**Comment by jb-alvarado** [comment]
I will check it, maybe is fixed already in master.

**Comment by SoftwareMagicIT** [comment]
I see only remove link created when install, issue fixed. You can close this
