### ISSUE TITLE
Add multiple times playlist for same day and scheduling

### ISSUE THREAD

**Issue by SoftwareMagicIT** [ffplayout/ffplayout-frontend#58]
Is possible adding multiple playlist for same day and scheduling system for allow to select same playlist in schedule grid?

**Comment by jb-alvarado** [comment]
No sorry, it is not possible and not planed. For a real scheduling system I have not the capacity.

**Comment by SoftwareMagicIT** [comment]
if you need and want I can help you for this.

**Comment by jb-alvarado** [comment]
What exactly do you mean by multiple playlists per day? When you mean multi channel support, that is integrated in the upcoming version.

When you are willing to develop and maintain a scheduling system, you are welcome to help!

**Comment by SoftwareMagicIT** [comment]
I mean a master playlist where it is possible to specify the times of the individual elements and each element can be a sequential or random playlist or a single video. In case of gaps in the times, the playlist before the video remains as a carpet to fill, up to the next element which can be another playlist or a specific video. Yes I would like to help you and I will start this week to study how the project is composed. I am a bit fast in the language you use and I need time, not long, to align. Also I would also like it if you could find an agreement for use on a commercial level, otherwise it doesn't matter, I will help you the same because I like it and at most I will only use it to play my personal web tv. If you are interested, we could hear from you via email, the address of my company is info@softwaremagic.it, write me there and we exchange emails and if you want also the number to hear us on whatsapp as soon as I can actively participate in the development.

**Comment by jb-alvarado** [comment]
I could image that this playlist functionality can be implement in the frontend. But for the engine it is to complicate and it also don't fit in our workflow.

You also need to know, that cross fading clips is not possible, so when your playlists would overlap, it could not correct use this in the engine.

You can see if you understand the code and if you could work with it. In python I try to be **PEP8** conform and I have started to check my code with **pylint**. This will be definitely a requirement for collaboration.

Normally we don't need a special agreement. The project can be used on a commercial level, but of course it must be conform with the license.

You should also know that I personally want to live a high moral standard. This also means for me that I don't want to give support for offensive, sensual and violence glorifying content.

When you are ok with that and you have studied the project, we write talk by mail.

**Comment by SoftwareMagicIT** [comment]
I agree with your view. As far as the license is concerned, I fully agree in compliance with the GPL, I thought I would only offer system support and installation for a fee, or alternatively, using ffmpeg LGPL we can agree on each installation. Now I will take advantage of the Easter holidays to study the structure. I also have an idea of how to do some things and it is not necessary for the contents to mix, if they want it mixed they will buy my commercial software that does. In the meantime, I continue to try your changes and report problems.
