### ISSUE TITLE
Some layout changes suggestions

### ISSUE THREAD

**Issue by SoftwareMagicIT** [ffplayout/ffplayout-frontend#59]
When compose playlist need to have empty space for insert after last element
![image](https://user-images.githubusercontent.com/16600519/112745836-93fdde80-8fab-11eb-9b1a-db498d66a31f.png)

You can change menu functionality for get this (image create with gimp)?

![image](https://user-images.githubusercontent.com/16600519/112745992-741aea80-8fac-11eb-8df0-c7283cf74a79.png)

**Comment by jb-alvarado** [comment]
Yes the first suggestion make sense, the second I need to think about - is more a question of taste and at the moment I don't like it :-).

**Comment by SoftwareMagicIT** [comment]
I work in TV and Radios like director and for some reasons needed operator show current content and if seeing this if logged. Sorry for my bad english. I think is best show player, time and controls in static header of page and change only sections without stop playing streaming and showing situation.

**Comment by jb-alvarado** [comment]
I though now about the global player header, and I will not change this. It makes the GUI less clean and it would make the chance more high that by accident you click a button what you don't want.
