### ISSUE TITLE
Time error (timezone)

### ISSUE THREAD

**Issue by SoftwareMagicIT** [ffplayout/ffplayout-frontend#61]
Hello, my timezone is UTC +2 (normally UTC+1 but for 7 months in daylight saving time). at this time (00:11 AM) player says 22:11 instead of 00:11.
Three possibles resolutions. First get time from browser or get time from server or add setting in playout section with UTC List and Daylight Saving months range.
Also I suggest create tabs for playout settings because too height page.
For all the others: good, your project is very awesome.

**Comment by Marco-LB** [comment]
basta sincronizzare il server con i server ntp italiani e non hai problemi per l'ora legale

**Comment by SoftwareMagicIT** [comment]
Fatto, l'ora del server è a posto ma la dashboard me la mostra 2 ore indietro.

**Comment by SoftwareMagicIT** [comment]
In ogni caso sto studiando la struttura, secondo come la implemento io e poi mando le modifiche.

**Comment by Marco-LB** [comment]
si hai ragione, ma il sistema manda dei flussi video, e cambiare in base ai fusi orari significa che il sistema dovrà mandare molti più flussi appesantendo il server

**Comment by SoftwareMagicIT** [comment]
L'idea del multicanale mi lascia perplesso perché l'ffmpeg è pesante. Ma ho installato ieri l'ultima versione master con le correzioni che ho suggerito e ho visto che è stato implementato. Questo vuol dire che dovrebbero partire tanti processi playout per quanti sono i canali implementati. Il peso sul sistema non cambia perché deve solo fare la somma dell'ora del server con l'UTC impostato. Io preferirei e vedrò come contribuire per questo, che venisse implementata invece la pianificazione, cioè una playlist giornaliera con orario ed elementi a due livelli di priorità. Uno basso che va sempre ed è una playlist e uno alto che interrompe la playlist all'ora specifica per riprodurre quanto impostato.

**Comment by SoftwareMagicIT** [comment]
Ora non è che dico che se sto in Italia sul ch1 deve mettere il fuso italiano e se ho un amico che sta in US deve mettere sempre il ch1 con un altro flusso. Invece dico che posso fare due "tv" una MiaTV-IT e una MiaTV-US con contenuti diversi, ma su MiaTV-IT impostare il fuso italiano e MiaTV-US quello di N.Y. Non so se sono riuscito a spiegarmi.

**Comment by Marco-LB** [comment]
si hai ragione, comunque il multi canale secondo me è indispensabile se si vuole mandare una flusso streaming abr

**Comment by jb-alvarado** [comment]
The new version will take the time from server, and there it is configurable.

**Comment by SoftwareMagicIT** [comment]
Not working. In production release show correct time, in master branch no! 
![image](https://user-images.githubusercontent.com/16600519/113016971-48039300-917f-11eb-8b29-e9ca0300d0f6.png)

**Comment by jb-alvarado** [comment]
That is, because the correct timezone has to be in API common.py.

**Comment by SoftwareMagicIT** [comment]
Ok, I change UTC with Europe/Rome and now work fine. I have also installed latest frontend and created virtual link for current mapping engine with channel1 (/etc/ffplayout/ffplayout.yml -> /etc/ffplayout/ffplayout-001.yml). Work reload, stop but not start and not restart. Error 500. I think missing a correct file, but which file is missing?

**Comment by jb-alvarado** [comment]
It is important that the timezone in **common.py** is the matching system timezone in **/etc/timezone**.

**Comment by SoftwareMagicIT** [comment]
Yes, in my system and in common.py is Europe/Rome

**Comment by edwoodza** [comment]
> 
> 
> It is important that the timezone in **common.py** is matching system timezone in **/etc/timezone**.

Install was done.
GUI shows server time using 
timedatectl set-timezone  xxxxx

confirmed set

rebooted server.

server shows new time

GUI does not.

I assume after installing and changing server time one needs to then edit a setup file again as it does not pick up time from server when changed?

please confirm and if edit needed which file needs editing to change config to servers new timezone




we updated server time from UTC

**Comment by SoftwareMagicIT** [comment]
you need to set also common.py with your timezone before compiling

**Comment by edwoodza** [comment]
could the set time option not be added in the installer to avoid this down the line maybe? @jb-alvarado
