### ISSUE TITLE
No playout config found after latest modifications

### ISSUE THREAD

**Issue by SoftwareMagicIT** [ffplayout/ffplayout-frontend#62]
![image](https://user-images.githubusercontent.com/16600519/113000845-804fa500-9170-11eb-9e37-0c33e1381c74.png)

I have uninstalled and reinstalled all from scracth but see always this

Note, issue seem in API request.

**Comment by jb-alvarado** [comment]
The master version from API and frontend needs more handwork to run. I still need to update the install instruction and the auto installer script.

**Comment by SoftwareMagicIT** [comment]
I have "mitigate" this using virtual link. Now work, but restart and play not working. How I can temporary solve this?

**Comment by jb-alvarado** [comment]
I just update the install instruction in every repo. This should help, but I have not widely test it. I try to finish this week a new install script, then it become more easy. The setup is very picky when it comes to permissions.

**Comment by SoftwareMagicIT** [comment]
ok but error 500 appears only if not find file. Because system work fine, only start and restart not working (for restart, stopped but not restarted), that's enough for now remember not to press stop or restart. 
![image](https://user-images.githubusercontent.com/16600519/113109874-b2abe180-9206-11eb-9d51-06771a62e00d.png)

**Comment by jb-alvarado** [comment]
I found some smaller errors, normally it should fixed now. You can also setup a single channel environment, without supervisord.

I also worked on the installer script, on debian it runs fine.

**Comment by SoftwareMagicIT** [comment]
Ok, thanks. now I try to reinstall all

**Comment by SoftwareMagicIT** [comment]
Work fine all except in media, error 500 renaming and deleting file. Error 500 after showmodal

**Comment by SoftwareMagicIT** [comment]
Good.

**Comment by testermania** [comment]
hi installed but cd: /var/www/ffplayout: No such file or directory

**Comment by SoftwareMagicIT** [comment]
Solved all issues
