### ISSUE TITLE
500 error in media or player tab

### ISSUE THREAD

**Issue by vijaykumarchettiar** [ffplayout/ffplayout-frontend#64]
@jb-alvarado The playoutool has good feature and encoding and output correctly. However when i want to generate playlist using /opt/media folder under media or player tab, it shows 500 error. Especially when there mp4 files under folder then it throws 500 error. But folder list shows without any error.

i checked the folder and file permission, everything read and writable.

please help me to fix this error.
![opt_media_error_500](https://user-images.githubusercontent.com/4214357/115066099-ac0eb100-9f0c-11eb-9e72-ba65cc30c1a9.png)

**Comment by jb-alvarado** [comment]
In which way have you install ffplayout?

Two things comes in my mind:

1. take care that the path to your media store is **/opt/media**, not **/opt**
2. the media folder needs a symlink to the static folder from frontend, but this symlink must exist before you run `npm run build`

**Comment by vijaykumarchettiar** [comment]
thanks for the reply.
yes did the same and rebuild it but still the same error.
![image](https://user-images.githubusercontent.com/4214357/115202113-afc05480-a113-11eb-8f6f-5e56fa5dcd54.png)

**Comment by vijaykumarchettiar** [comment]
pls refer the console log in the browser...

**Comment by jb-alvarado** [comment]
Can you post for yaml Config? At the moment you don't need to rebuild the API. I think it is a configuration issue.

**Comment by vijaykumarchettiar** [comment]
@jb-alvarado 
yes here attached the yaml config file which used by the front end interface.
general:
    helptext: Sometimes it can happen, that a file is corrupt but still playable,
        this can produce an streaming error over all following files. The only way
        in this case is, to stop ffplayout and start it again here we only say it
        can stop, the starting process is in your hand. Best way is a systemd serivce
        on linux. 'stop_threshold' stop ffplayout, if it is async in time above this
        value.
    stop_on_error: true
    stop_threshold: 11
mail:
    helptext: Send error messages to email address, like missing playlist; unvalid
        json format; missing clip path. Leave recipient blank, if you don't need this.
        'mail_level' can be WARNING or ERROR.
    subject:  Playout Error
    smpt_server: mail.example.org
    smpt_port: 587
    sender_addr: ffplayout@example.org
    sender_pass: abc123
    recipient: null
    mail_level: ERROR
logging:
    helptext: Logging to file, if 'log_to_file' False log to console. 'backup_count'
        says how long log files will be saved in days. Path to /var/log/ only if you
        run this program as deamon. 'log_level' can be DEBUG, INFO, WARNING, ERROR.
        'ffmpeg_level' can be INFO, WARNING, ERROR.
    log_to_file: true
    backup_count: 7
    log_path: /var/log/ffplayout/
    log_level: DEBUG
    ffmpeg_level: ERROR
processing:
    helptext: Default processing, for all clips that they get prepared in that way,
        so the output is unique. 'aspect' must be a float number. 'logo' is only used
        if the path exist. 'logo_scale' scale the logo to target size, leave it blank
        when no scaling is needed, format is 'number:number', for example '100:-1'
        for proportional scaling. With 'logo_opacity' logo can become transparent.
        With 'logo_filter' 'overlay=W-w-12:12' you can modify the logo position. With
        'use_loudnorm' you can activate single pass EBU R128 loudness normalization.
        'loud_*' can adjust the loudnorm filter. 'output_count' sets the outputs for
        the filtering, > 1 gives the option to use the same filters for multiple outputs.
        This outputs can be taken in 'ffmpeg_param', names will be vout2, vout3; aout2,
        aout2 etc.'use_realtime' is realtime filter, it works not in all scenarios,
        but for example is necessary for hls output.
    width: 1024
    height: 576
    aspect: 1.778
    fps: 30
    add_logo: true
    logo: docs/logo.png
    logo_scale: null
    logo_opacity: 0.7
    logo_filter: overlay=W-w-12:12
    add_loudnorm: false
    loud_I: -18
    loud_TP: -1.5
    loud_LRA: 11
    output_count: 1
    use_realtime: false
playlist:
    helptext: Set 'playlist_mode' to 'False' if you want to play clips from the 'storage'
        section. Put only the root path here, for example '/playlists' subfolders
        are readed by the script. Subfolders needs this structur '/playlists/2018/01'
        (/playlists/year/month). 'day_start' means at which time the playlist should
        start, leave day_start blank when playlist should always start at the begin.
        'length' represent the target length from playlist, when is blank real length
        will not consider.
    playlist_mode: false
    path: /playlists
    day_start: ''
    length: '24:00:00'
storage:
    helptext: Play ordered or ramdomly files from path. 'filler_clip' is for fill
        the end to reach 24 hours, it will loop when is necessary. 'extensions' search
        only files with this extension. Set 'shuffle' to 'True' to pick files randomly.
    path: /media/external/swig/ChanAllAssetFiles
    filler_clip: /media/external/swig/ChanAllAssetFiles/dstv
    extensions:
    - .mp4
    - .mkv
    shuffle: true
text:
    helptext: Overlay text in combination with libzmq for remote text manipulation.
        On windows fontfile path need to be like this 'C\:/WINDOWS/fonts/DejaVuSans.ttf'.
        In a standard environment the filter drawtext node is Parsed_drawtext_2. 'over_pre'
        if True text will be overlay in pre processing. Continue same text over multiple
        files is in that mode not possible. 'text_from_filename' activate the extraction
        from text of a filename. With 'style' you can define the drawtext parameters
        like position, color, etc. Post Text over API will override this. With 'regex'
        you can format file names, to get a title from it.
    add_text: false
    over_pre: false
    bind_address: 127.0.0.1:5555
    fontfile: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
    text_from_filename: false
    style: x=(w-tw)/2:y=(h-line_h)*0.9:fontsize=24:fontcolor=#ffffff:box=1:boxcolor=#000000:boxborderw=4
    regex: ^(.*)_
out:
    helptext: The final playout compression. Set the settings to your needs. 'mode'
        has the standard options 'desktop', 'hls', 'stream'. Self made outputs can
        be define, by adding script in output folder with an 'output' function inside.
        'stream_output' is for streaming output, two ffmpeg instances are fired up,
        for pre- and post-processing. 'hls_output' is for direct output to hls playlist,
        without pre- and post-processing, mode must be 'hls'.
    mode: stream
    service_name: Live Stream
    service_provider: Vijaykumar 
    ffmpeg_param: -c:v libx264 -crf 23 -maxrate 1300k -bufsize 2600k -preset medium
        -profile:v High -level 3.1 -c:a aac -ar 44100 -b:a 128k
    stream_output: -flags +global_header -f flv rtmp://localhost:1935/live/51455
    hls_output: -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist+program_date_time
        -hls_segment_filename /var/www/srs/live/stream-%09d.ts /var/www/srs/live/stream.m3u8

**Comment by vijaykumarchettiar** [comment]
@jb-alvarado the config yml file as same as original from repository, i only changed the storage path. please review and let me if anything i missed related the 500 error

**Comment by jb-alvarado** [comment]
filler_clip should be a clip, not a folder, but that is not the case here.

Can you post here the result of `ls -alh /media/external/swig/ChanAllAssetFiles/`?

**Comment by vijaykumarchettiar** [comment]
drwxrwxr-x 3 www-data www-data 4.0K Apr 16 21:35 .
drwxr-xr-x 8 www-data www-data 4.0K Apr 16 21:35 ..
drwxrwxrwx 2 www-data www-data  12K Apr 17 07:59 dstv

**Comment by vijaykumarchettiar** [comment]
@jb-alvarado folder list works fine, but when there is mp4 or mkv files under that folder and when go inside that folder then 500  error shows.
all media files has same owner and permission as same as folder

**Comment by jb-alvarado** [comment]
> In which way have you install ffplayout?

Can you also say something to that question? Did you follow manually install instruction, or did you use the automatic install script?

**Comment by vijaykumarchettiar** [comment]
i installed stand alone of engine, front end, api, srs and ffmpeg etc and everything run through system ctrl... which works fine...

**Comment by jb-alvarado** [comment]
Is there something strange in `systemctl status ffpalyout-api`?
Have you install mediainfo?

**Comment by vijaykumarchettiar** [comment]
ffplayout-api.service - ffplayout api daemon
     Loaded: loaded (/etc/systemd/system/ffplayout-api.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-03-13 04:04:34 CET; 1 months 7 days ago
   Main PID: 486 (gunicorn)
      Tasks: 5 (limit: 9486)
     Memory: 250.4M
     CGroup: /system.slice/ffplayout-api.service

**Comment by vijaykumarchettiar** [comment]
@jb-alvarado 
Apr 19 15:15:59 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:15:59 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 615 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:01 playout gunicorn[575]: 127.0.0.1 - - [19/Apr/2021:13:16:01 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 613 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:01 playout gunicorn[573]: 127.0.0.1 - - [19/Apr/2021:13:16:01 +0000] "GET /api/player/media/?extensions=.mp4,.mkv,.jpg,.jpeg,.png&path= HTTP/1.0" 200 49 ">
Apr 19 15:16:03 playout gunicorn[574]: 127.0.0.1 - - [19/Apr/2021:13:16:03 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 613 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:06 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:06 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 617 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:07 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:07 +0000] "GET /api/player/media/?extensions=.mp4,.mkv,.jpg,.jpeg,.png&path=/ChanAllAssetFiles/>
Apr 19 15:16:08 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:08 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 622 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:10 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:10 +0000] "GET /api/player/media/?extensions=.mp4,.mkv,.jpg,.jpeg,.png&path=/ChanAllAssetFiles/>
Apr 19 15:16:10 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:10 +0000] "GET /api/player/stats/?stats=all HTTP/1.0" 200 625 "http://10.13.37.234/" "Mozilla/5>
Apr 19 15:16:14 playout gunicorn[576]: 127.0.0.1 - - [19/Apr/2021:13:16:14 +0000] "GET /api/player/media/?extensions=.mp4,.mkv,.jpg,.jpeg,.png&path=/ChanAllAssetFiles/>

**Comment by vijaykumarchettiar** [comment]
> Have you install mediainfo?

what's is it? is npm packages?

**Comment by vijaykumarchettiar** [comment]
> > Have you install mediainfo?
> 
> what's is it? is npm packages?

venv/lib/python3.8/site-packages/pymediainfo 
there is python library under api directory path

**Comment by jb-alvarado** [comment]
`apt install mediainfo`

**Comment by vijaykumarchettiar** [comment]
> `apt install mediainfo`

yes it works now... thank a lot.

**Comment by edwoodza** [comment]
having same error here too.
@vijaykumarchettiar  what was it that make it work for you?

I can upload files into the root directory no problem
BUT 
when i try create a Directory i get the error

![po err](https://user-images.githubusercontent.com/8553968/117118248-d8418300-ad90-11eb-91ec-a3be6ea67a7d.png)

**Comment by vijaykumarchettiar** [comment]
> having same error here too.
> @vijaykumarchettiar what was it that make it work for you?
> 
> I can upload files into the root directory no problem
> BUT
> when i try create a Directory i get the error
> 
> ![po err](https://user-images.githubusercontent.com/8553968/117118248-d8418300-ad90-11eb-91ec-a3be6ea67a7d.png)

check the folder permission which has read/write permission

**Comment by edwoodza** [comment]
i can write files just not create folders,

**Comment by edwoodza** [comment]
did a clean install this morning again using the installer.

Media I can upload files the root folder
BUT
When i create a folder via GUI it errors code500
can create folder via terminal no problem 
BUT if i then upload a file to the folder created in terminal GUI does not upload.

I took a look through the above and did not find any folder rights issues.
did a second clean install as well to confirm i did not do something stupid

**Comment by vijaykumarchettiar** [comment]
> did a clean install this morning again using the installer.
> 
> Media I can upload files the root folder
> BUT
> When i create a folder via GUI it errors code500
> can create folder via terminal no problem
> BUT if i then upload a file to the folder created in terminal GUI does not upload.
> 
> I took a look through the above and did not find any folder rights issues.
> did a second clean install as well to confirm i did not do something stupid
> 
> @jb-alvarado ?
Did you install in linux environment? 
this will solve your problem.
apt install mediainfo

**Comment by edwoodza** [comment]
Deb10 clean yes.
i tried the mediainfo but its already installed so not missing.

**Comment by jb-alvarado** [comment]
Was a bug and is fixed in new release.

Please create next time a new issue. This makes it more easy for me and people with same problems.

**Comment by edwoodza** [comment]
I created new install today using latest release and had same bug.

I did create a new issue with this and another one i found in GUI
I think the 2 may be related
