### ISSUE TITLE
GUI config write error 400

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#68]
installed new clean using the v3 playout installer on deb10
single playout.

V3.2.0 engine
V3.0.2 GUI
V3 API
V3.0.0 installer

all is good
but occasionally see error on file upload. then goes away. i know this was an issue before and was fixed but seems somehow to be back. 

*EDIT* now as of this am even login screen errors with this. can not login access or use gui

also when trying to change items in the GUI menu and save it does not save and errors. Am unable to make changes to the GUI part of the config menu.
Playout config side i can change no problem

![po31](https://user-images.githubusercontent.com/8553968/120198343-45c2c100-c222-11eb-8f19-9cb721385882.png)

**Comment by edwoodza** [comment]
weird. rebooting server made no change
BUT when i logged into GUI local 127.0.0.1 then all outside access error went away (even login)

The only code 400 now is on config--GUI

**Comment by edwoodza** [comment]
also tried clearing cookies before with little change.
also tried on several different pc and browsers as well to replicate. they all showed the 400 error

**Comment by edwoodza** [comment]
the error seems to kick in when uploading LARGE video files. smaller files is ok.
so it seems like something times out maybe?

**Comment by jb-alvarado** [comment]
400 error should be fixed now.

**Comment by edwoodza** [comment]
when was the changed pushed?
is the fix fixed with the installer command as well

**Comment by edwoodza** [comment]
will this fix also fix the uploading of big files timing out with error as well?

**Comment by jb-alvarado** [comment]
> is the fix fixed with the installer command as well

Yes

> will this fix also fix the uploading of big files timing out with error as well?

How big is the file?

**Comment by edwoodza** [comment]
some files are 3,300,300KB but uploading on 1gbs line plus so fast should not reach the 180min timeout at all

**Comment by edwoodza** [comment]
must I update front end AND api or just front end for this fix?

**Comment by jb-alvarado** [comment]
Only the API, best ist to remove **/var/www/ffplayout-api** and install it new.

**Comment by edwoodza** [comment]
created clean new server using installer
the saving GUI settings bug fixed

BUT large file uploads still fail with code 500
![Uploading po1june22.png…]()

**Comment by jb-alvarado** [comment]
You need to figure out, if the errors comes from nginx. This you see in the browser console. When the error comes from nginx you have to inspect the nginx error log. A very simple error could be, that your root system has not enough free space.

**Comment by edwoodza** [comment]
not a drive space issue, that was the 1st thing checked before hand. had 100x more space than the 1 file.
its like something times out in transfer on big files even if its fast connection

**Comment by edwoodza** [comment]
will test this next week with the new installer and updates applied again

**Comment by edwoodza** [comment]
when changing dns name to server eg in install we used xyz.com
we change to zyp.com 
BOTH same IP
the login gives error 
"Error: Request failed with status code 400"
but if i login with the IP all is ok.

**Comment by edwoodza** [comment]
tested friday and was fixed
new install today and errors again

**Comment by jb-alvarado** [comment]
You can use the installer version from release. The master branch is not always stable.

**Comment by edwoodza** [comment]
I only see the following for installer:

master 3 days old
dev 2 months old
v1.0.0 13 months old

**Comment by jb-alvarado** [comment]
I was talking about this one: https://github.com/ffplayout/ffplayout-installer/releases/tag/v3.1.0

**Comment by edwoodza** [comment]
will give it another try
