### ISSUE TITLE
Changing log directory broke playout

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#69]
Latest updates install clean on deb.
all working good and the last few bugs cleared (other than big file uploads)

BUT when i changed the directory for the log files and saved it. it seemed to break the server it does not go into playout again after restarts.
I changed the log file diretcory back and restarted same issue
playout does not start and i cant see any logs in GUI
also nothing written to /var/log/ffplayout either

**Comment by edwoodza** [comment]
checked log directory permissions comparing to another server and they all the same.

**Comment by edwoodza** [comment]
yeah its a bug
not sure if its created before or after i edit the config-->GUI
but after that i see no logs and playout does not work.

have not changed log directory and am seeing zero logs of any info

I did not even get as far as to edit the video location files etc (but those have no issue)

**Comment by jb-alvarado** [comment]
I'm not able to reproduce this.

**Comment by edwoodza** [comment]
Install was done with single channel mode not multi. 
That may be the reason it's not replication ?

**Comment by edwoodza** [comment]
i removed /var/www/ffplayout-frontend as well as API
and downloaded installer again and ran it

did it 2x. both times clean no logs show and playout wont start playing

i did it with single channel and multi channel install
http and https as well

both render same results, server not working to playout, nor any logs showing

**Comment by edwoodza** [comment]
just did a full clean install using installer on deb10
using single channel setup
and when server comes up. it does not produce any logs and it will not start playout or will playout play out.
1% CPU use as well confirming not running.

**Comment by edwoodza** [comment]
also the GUI is now so slow it times out and is not usable (this is on clean new machine when i started to test if all else was ok
i add a file and tell the system to loop it, that takes a few min before i can save and gui locks up

this is on a clean install too using the installer current ver

**Comment by jb-alvarado** [comment]
I needed to add a new engine release and update the installer. There was some old paths in it. You need install everything new.

**Comment by edwoodza** [comment]
ok, testing now will advise

**Comment by edwoodza** [comment]
Just tested seems the updates fixed it.
will do more extensive testing monday. have run out of week

**Comment by edwoodza** [comment]
retested with new install today and issues back
cant view logs 
playout does not start on clean install

use name server not ip address on install

**Comment by jb-alvarado** [comment]
Please don't double post everywhere.

**Comment by edwoodza** [comment]
not, just updating each thread which were separate issues so you are aware of effects on each item separately to make your life easier
