### ISSUE TITLE
Receive multiple outputs from a server

### ISSUE THREAD

**Issue by burakguder** [ffplayout/ffplayout-frontend#71]
Hello

I like your work very much. There is no other application that works on such a detailed and simple structure.

My question.
Can I have more than one playlist output on a 32 core server?

maybe i can achieve this by running node on different ports?

**Comment by jb-alvarado** [comment]
Hello,
for this normally I created the multi channel support. With that you can run multiple ffplayout engine instances and every one has its own config and playlists. When you install everything with the ffplayout-installer, you have to select multi channel support.

This feature is relatively new and not so much tested, then the single mode. But give it a try an see if it works for you.
