### ISSUE TITLE
RTMP re-stream 

### ISSUE THREAD

**Issue by Waffleuncle** [ffplayout/ffplayout-frontend#73]
Hi , 
I was looking for streaming on RTMP but i dont find the doccumentation about it. 
Can you show me some exemple or screenshot where can i simply put my RTMP info on interface

**Comment by jb-alvarado** [comment]
You go to **Configure** -> **Playout** and then down to **Out**.

**Comment by ScoobyDooWaffle** [comment]
SORRY FOR MOMENT I WAS UNABLE TAKING ANY E_MAIl i GET SERIOUS INJURY ON EMAIL SERVER
