### ISSUE TITLE
Cannot access web front end with ethernet unplugged

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout-frontend#86]
Ubuntu 21.10 if I unplug ethernet, I cannot load the web front end.  I am on http://192.168.1.89/..  once I unplug, or switch to wifi, and try to load that address it always tries but does not load.  Any advice? Thanks

**Comment by jb-alvarado** [comment]
When your computer is not plugged to the router, the IP is not valid any more. You have two options: give your computer a static IP, or use your localhost in the nginx config - but then the frontend is not available over the network.

**Comment by tvadi** [comment]
Got it, thanks!
