### ISSUE TITLE
Ingest 

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#88]
Hi
Regarding ingest function on GUI.

1. Am i correct to understand that the values in input_stream when detected its live interupts the output_param output set
and switches back output_param when input_stream ends?

OR
does output_param stay the same but it uses input_stream instead of the playlist

2. Can the value in input-stream be external server links or must it be local

3. Also input_stream what formats does it accept, DASH, HLS, etc or just RTMP?

**Comment by jb-alvarado** [comment]
The output will not interrupt, when an ingest is recognised, it only switch the source from playlist to live ingest.

As input you can use all kinds of live streams, which are supported from ffmpeg. DASH and HLS are not live streams. For example you could use: rtmp, srt, rtp, udp, etc.

**Comment by edwoodza** [comment]
HLS and Dash can be live streams though.
I will give it a test with udp and SRT next week.
I did try RTMP but gave errors.
I will retry next week and send results and logs that come up

**Comment by edwoodza** [comment]
I used a rtmp stream for the ingest.
saved it
and restarted server from GUI:

[2022-04-11 08:19:37,641] [ERROR]  [Server] [rtmp @ 0x55f593010600] Cannot open connection tcp://stream.abc.tv:1935?listen&listen_timeout=-1000&tcp_nodelay=0
[2022-04-11 08:19:37,642] [ERROR]  [Server] rtmp://stream.abc.tv:1935/live/ztv/ztv: Cannot assign requested address

(stream tested playing in VLC before using it and runs from my test streaming server as well so no DRM etc)
not sure why i uses tcp:// and not rtmp:// that was entered?

I also used a SRT "stream"
and got:


[2022-04-11 08:24:52,806] [WARNING]  Ingest stream is experimental, use it at your own risk!
[2022-04-11 08:24:52,807] [DEBUG]  Server CMD: "ffmpeg -hide_banner -nostats -v level+error -f live_flv -listen 1 -i srt://streamtv.tv:5009 -filter_complex [0:v]fps=25,scale=1024:576,setdar=dar=1.778[v];movie=/opt/tv-media/logo/HD.png,loop=loop=-1:size=1:start=0,format=rgba,scale=100:-1,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-12:12:shortest=1[vout1] -map [vout1] -map 0:a -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a mp2 -b:a 384k -ar 48000 -ac 2 -f mpegts -"
[2022-04-11 08:24:52,855] [INFO]  Open: /opt/playlists/2022/04/2022-04-11.json
[2022-04-11 08:24:52,855] [DEBUG]  List init
[2022-04-11 08:24:52,873] [INFO]  Play: /opt/tv-media/test720P.mp4

and it does not play the live SRT

**Comment by edwoodza** [comment]
I might suggest for live:

rather than auto switch which is open to many issues
have a button on main player page to push LIVE out and toggle between playlist and LIVE.
that removed the auto function that could cause lives to go live at wrong times and or stop when live

**Comment by jb-alvarado** [comment]
Check your firewall that the ports are open and try this settings for rtmp ingest:

```
-f live_flv -listen 1 -i rtmp://[PUBLIC IP]:1936/live/stream
```
> rather than auto switch which is open to many issues have a button on main player page to push LIVE out and toggle between playlist and LIVE. that removed the auto function that could cause lives to go live at wrong times and or stop when live

When you have a pull request for that, I will think about to integrate this.

I'm not really recommend to listen with ffmpeg on a public port. Use a [patched](https://gist.github.com/jb-alvarado/f8ee1e7a3cf5e482e818338f2b62c95f) version which allow address restriction or a relay with authentication.

**Comment by edwoodza** [comment]
Firewall not blocking anything. 
I confirmed that to eliminate it.

I used the -f live_flv -listen 1 -i rtmp://[PUBLIC IP]:1935/live/stream as well and no luck (my streaming server serves it out on 1935. and i pull from there into ingest)

I have successfully use ffmpeg to pull in RTMP, HLS, DASH, RIST, SRT and convert it to other formats. So in theory ingest should allow these as well with success.

I guess the auto switching side is where it gets messy.

GUI LIVE button to toggle on and off may be simplest way then it just directs the MMPEG compatible stream to input and terminates playlist and encoded on output

**Comment by edwoodza** [comment]
does UDP and the rest work with the live_flv setting?
is that not specific to rtmp only?

**Comment by jb-alvarado** [comment]
You can also run ffmpeg directly an see if it works:

```
ffmpeg -f live_flv -listen 1 -i rtmp://[PUBLIC IP]:1936/live/stream -f null -
```

**Comment by edwoodza** [comment]
the 1936 port number you using. std is 1935.
is there a reason for 1936?

eg my wowza streaming server for testing that i pasted into ingest is rtmp://servername.tv:1935/live/channel  not 1936
so playout ingest pulls from my wowza test server rtmp

**Comment by edwoodza** [comment]
i tried the command above
But get the error:

Trailing option(s) found in the command: may be ignored.
[rtmp @ 0x563ee724df40] Cannot open connection tcp://stream.abc.tv:1935?listen&listen_timeout=-1000&tcp
_nodelay=0
rtmp://stream.abc.tv:1935/live/abc/abc: Cannot assign requested address

This rtmp link can however be opened and played in VLC which confirms not a firewall issue

**Comment by jb-alvarado** [comment]
Maybe this is a miss understanding about client and server connections? The ffplayout ingest get not pull anything, it can only act as a server.

**Comment by edwoodza** [comment]
so you saying it only functions as a wowza replacement for ingest?
and you cant use wowza as main stream server and have ingest pull the stream from the wowza server (which is a much simpler application for live)

To avoid more misunderstandings.
Must we only use SRS for live?
OR
can we install a wowza on the server and use that rather?

OR

Must we set wowza to push the stream to SRS input?

sorry i am very confused now as to how ingest works best and simplest

**Comment by jb-alvarado** [comment]
Ingest pull can not work, because how should ffplayout know when there is a stream coming or not?
 
I would suggest, if wowza support this:

1. install wawza on the same machine 
2. use for ingest only a local IP (127.0.0.1)
3. make in make wowza a dedicated entry point only that purpose
4. for your authentication with wowza
5. forward the stream to the ffplayout ingest.

**Comment by edwoodza** [comment]
what are the ffplayout ingest settings to config wowza with?
so we can be sure we using the correct config ffplayout is expecting.

i assume SRS then tells ffplayout the input is live?
It may be simpler to just use ffmpeg to pull live streams (hls, dash, udp etc) and enable disable with a LIVE button on GUI and if the input is dead it uses filler.
OR Button turns green when live stream is live, then you can click enable live to put it on air. (so green is ffmpeg saying stream is live and good to go) 

then no need for the other configurations that may make a simple live add complex.
and also avoids security issues on server?
and issues of it auto thinking and interrupting playout

**Comment by jb-alvarado** [comment]
There are no special configs. set your ffplayout ingest settings to something like:

```
-f live_flv -listen 1 -i rtmp://[PUBLIC IP]:[your free port]/live/stream
```
and the stream/forward to that address.

For testing:
```
ffmpeg -re -i input.mp4 [codec settings] -f flv rtmp://[PUBLIC IP]:[your free port]/live/stream
```

**Comment by edwoodza** [comment]
i am pushing RTMP to the ffplayout srs
its connected and pushing on the streaming software
but now get this error in logs

[2022-04-11 14:04:35,791] [ERROR]  [Server] rtmp://127.0.0.1:1935/live/stream: Address already in use
[2022-04-11 14:04:36,128] [ERROR]  [Server] [rtmp @ 0x56155d26c600] Cannot open connection tcp://127.0.0.1:1935?listen&listen_timeout=-1000&tcp_nodelay=0
[2022-04-11 14:04:36,471] [ERROR]  [Server] [rtmp @ 0x557325c55600] Cannot open connection tcp://127.0.0.1:1935?listen&listen_timeout=-1000&tcp_nodelay=0
[2022-04-11 14:04:36,472] [ERROR]  [Server] rtmp://127.0.0.1:1935/live/stream: Address already in use

i am not pushing playout output to SRS (its running udp so i can check real time output)
so not a case or 2 streams connected

**Comment by jb-alvarado** [comment]
And have you check which program use the port?

**Comment by edwoodza** [comment]
1936 does it need to be configured at all for SRS on server? will it work by default? 
Firewall is open for 1935-1936

but when i port scan 1936 it does not see anything.

**Comment by edwoodza** [comment]
I TOO am spending a lot of time and money to test and bug find for you, now and previously over the last few years.

But when there is little info on things i can only work with that there is.

Not knowing Exactly how the live system works and is setup makes it hard to test and give feedback that's useful and not a waste of time.

**Comment by jb-alvarado** [comment]
At the moment it look like, that you are using srs, but before you say you would like to use wawza. ffplayout is not depending on srs, so I would suggest, use srs or wowza, but not both.

When you use port 1936 for ingest, your stream to that ingest have to use port 1936 to.

**Comment by edwoodza** [comment]
I reverted back to UDP testing again as its better and simpler than RTMP
Using a video transport stream on multicast on 224.2.2.2:1234

![ff12apri2](https://user-images.githubusercontent.com/8553968/162911337-cee61971-af2c-44a1-a155-2c994ebcfa88.png)

I can see ffmpeg is now active on that on pid 9414

FF logs show
![ff12apirl3](https://user-images.githubusercontent.com/8553968/162911808-1551f4b9-3523-43ff-a127-b8281ed4626c.png)

And playout is still running off playlist. not switched to the UDP input to the main output encode (which i use 224.1.1.1:1234 so i can see real time the output of the server for testing

**Comment by edwoodza** [comment]
> At the moment it look like, that you are using srs, but before you say you would like to use wawza. ffplayout is not depending on srs, so I would suggest, use srs or wowza, but not both.
> 
> When you use port 1936 for ingest, your stream to that ingest have to use port 1936 to.

Yes. i removed wowza as it was not clear how live ingest was setup so i went back to basics. with little to no luck.

As above i tried UDP multicast which is totally separate of RTMP which is a painful protocol anyhow and UDP less messy.
But same results

**Comment by jb-alvarado** [comment]
That I have try to explain before, that will not work. You can only stream directly to the ingest. When you create a multicast stream, or rtmp for pull, or any other method including DASH or HLS, it can not work.

The ingest stream works in that way, that it runs a ffmpeg instance in **listening** mode, and as soon as it gets something in it will send it to a internal queue, and when this queue fills up, the engine knows that it have to switch from playlist to the live ingest.

**Comment by edwoodza** [comment]
> The output will not interrupt, when an ingest is recognised, it only switch the source from playlist to live ingest.
> 
> As input you can use all kinds of live streams, which are supported from ffmpeg. DASH and HLS are not live streams. For example you could use: rtmp, srt, rtp, udp, etc.

You stated UDP works earlier. So i am confused now

since i am using udp://224.2.2.2:1234 (in the ingest config) which us a UDP multicast created separately on network as UDP on udp://224.2.2.2:1234
Now you say UDP does not work.

I know i am having a rough week here and mind is melted with all my projects but its stated UDP works.
I use UDP
and told does not work.

I know its my lack of bigger picture of how the ingest engine works maybe but the missing pieces of the puzzle i cant find to get it working.

IF I am to use UDP. What must i do then? 
Because it seems just entering the UDP://224.2.2.2:1234 of the udp multicast thats live on the network and machine already is incorrect.

**Comment by edwoodza** [comment]
Let me know when SRT is good to use (although it has its moments as well)
I find UDP (which ffmpeg loves i use it everywhere) is most stable and easy to use as well. Hence why i went to go with it)

I did try SRT at the start but same results. May be needing extra items in the string for SRT maybe?

RTMP became hell and messy as ffmpeg is looking on TCP6 for it on port 1936 and not TCP and not sure why that is or how to fix it for fear of breaking things in the process which in tern creates bugs that give bad feedback.

**Comment by edwoodza** [comment]
Got rtmp working using a separate ffmpeg to pull the stream from server and then push locally to 1936. and it switches.

This approach may be the way to go to make it work simpler.
EG: in the ingest line, you fill on the live stream link.

Then it invokes a new ffmpeg to pull the stream and push it to 127.0.0.1:1936 using the streamlink in ingest line (then can work for all protocols easily too as its a copy from live stream to 1936 so one code for all protocols?

Just a thought

**Comment by edwoodza** [comment]
RTMP i am seeing takes 40 seconds to cut in and away from playlist.
is this normal?
is there a way to reduce this delay?

**Comment by jb-alvarado** [comment]
Yes that could work, but I would like to let this up to the user, so he have here more flexibility.

I just saw, that with wowza you have also the option to forward the stream, also with a non standard port:
https://www.wowza.com/docs/how-to-use-rtmp-to-distribute-live-streams
https://www.wowza.com/docs/how-to-push-streams-to-cdns-and-other-services-push-publishing

And with SRS you would use forward:
https://github.com/ossrs/srs/wiki/v3_EN_SampleForward

When you directly stream to ingest the delay should be around 5 seconds. You can optimize ffmpeg more for less delay, with **tune** and other options, but you need to make a little research. I have them not in mind.

**Comment by jb-alvarado** [comment]
Ok. That is why I try to have not to much dependencies to other projects. Personally I like SRS, but every other streaming platform if fine and I let the choice to the user.

**Comment by edwoodza** [comment]
Might it not be simpler to use ffmpeg for ingest to fill in the live stream link
then use ffmpeg in back to copy this stream to main output.

simplifies the back end of things and reduces complexities and its a one code fits all. And just fill in live link into ingest line (no other special notation needed) and it copies.

just a thought. i always try simplify things. i have a tendency to over complicate my life

**Comment by edwoodza** [comment]
I am noticing each time it switches from playout to live ingest there is 5 dropped frames on video.
This is consistently there.
but only when it goes from playout to live
not live back to playout.

any ideas on what that could be?

I notice a short cross fake when live ends back to playlist. could this be the cause at the dropped frames at the start?

**Comment by jb-alvarado** [comment]
At the moment I use already the most simple method. Every other ffmpeg instance on top will be more prone to error, add delay, cost more CPU usage and maybe quality lose.

It can be that there little glitches on switch. The way of switching is a bit rough and for that I am very grateful that it is still stable. Is not like in OBS and technically it is not possible to make it smoother.

Soon I will replace the engine, because I have change the code language to Rust, maybe there is a bit better.

**Comment by jb-alvarado** [comment]
I think, this ingest settings can reduce more the delay:

```
-probesize 32 -f live_flv -listen 1 -i rtmp://localhost:1936/live/stream -fflags nobuffer -flags low_delay
```
But I don't know if there is any side effects.

**Comment by edwoodza** [comment]
I will give that a try and place it on soak testing.
The existing one seems to do well other than large delay. But RTMP in i think the buffer is wise (although it adds the delay)

Not seeing any performance issues when i did a 6 hour soak test with it as well which is good.
