### ISSUE TITLE
Now playing does not update

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-frontend#89]
v4
Am testing infinite playlist with 1 clip.

I am seeing the "playing now" does not update correctly.

I had a full days playlist loaded and playing,
I deleted it. saved day clean.
added 1 file.
saved it
then reloaded

its playing the 1 file and encoding it,  but the "now playing" still shows the old file before i deleted list and made changed"

I left it playing for a while and it did not update.
I also reloaded browser as well no change but
When i did it showed no clips playing, however it was playing and encoding to output.

also file counter not updating (likely linked to now showing playing now
If i click loop clips. fill the day and save. then reload. OPS is normal and all displays correctly.

Nowthing showing in logging, so i assume its GUI bug related to infinite?

![ff7april](https://user-images.githubusercontent.com/8553968/162139165-6a044e92-1b57-434f-aafb-fac9325411cc.png)

**Comment by jb-alvarado** [comment]
I will take a look to it, in the next days.

**Comment by edwoodza** [comment]
It was similar to a previous bug that was fixed
so i assume its similar as it only happens with the new infinite option.
so should be a easy fix.

Nice work though on the update btw

**Comment by jb-alvarado** [comment]
Did you set `day_start` and `length` to **24:00:00** in the config? And have you an idea of how many items your playlist has?

When you also have one item in the playlist and that start time is in the past - there will be no clip playling (only a dummy one).

**Comment by edwoodza** [comment]
Yes start date and length is set. 24 hour playlist has no issue.
i created a 24 hour list, it was playing.

i then deleted the list and added a few items to use the infinite option.
The few files in the playlist DID playout
BUT
The GUI did not show "now playing" nor did it have the counter working for the file being played.

**Comment by jb-alvarado** [comment]
@edwoodza, sorry that I never responded! I worked on a new engine and now I created also a new frontend. I think this problem is solved.
